-- MySQL Script generated by MySQL Workbench
-- dom 28 nov 2021 09:08:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema challengeDois
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema challengeDois
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challengeDois` ;
USE `challengeDois` ;

-- -----------------------------------------------------
-- Table `challengeDois`.`status_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengeDois`.`status_orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengeDois`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengeDois`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengeDois`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengeDois`.`administradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `admin_master` TINYINT NOT NULL DEFAULT 0,
  `token` VARCHAR(500) NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengeDois`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengeDois`.`orcamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientes_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `valor_total` DOUBLE(12,4) NOT NULL,
  `pdf_url` VARCHAR(500) NOT NULL,
  `token` VARCHAR(500) NULL,
  `status_orcamento_id` INT NOT NULL,
  `motivo_status_orcamento` TEXT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  `administradores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamentos_clientes_idx` (`clientes_id` ASC),
  INDEX `fk_orcamentos_status_orcamento1_idx` (`status_orcamento_id` ASC),
  INDEX `fk_orcamentos_administradores1_idx` (`administradores_id` ASC),
  CONSTRAINT `fk_orcamentos_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `challengeDois`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentos_status_orcamento1`
    FOREIGN KEY (`status_orcamento_id`)
    REFERENCES `challengeDois`.`status_orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentos_administradores1`
    FOREIGN KEY (`administradores_id`)
    REFERENCES `challengeDois`.`administradores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
