-- MySQL Script generated by MySQL Workbench
-- seg 08 nov 2021 19:37:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema segundo_desafio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema segundo_desafio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `segundo_desafio` ;
USE `segundo_desafio` ;

-- -----------------------------------------------------
-- Table `segundo_desafio`.`administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segundo_desafio`.`administradores` ;

CREATE TABLE IF NOT EXISTS `segundo_desafio`.`administradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `admin_master` TINYINT NOT NULL DEFAULT 0,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segundo_desafio`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segundo_desafio`.`clientes` ;

CREATE TABLE IF NOT EXISTS `segundo_desafio`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf/cnpj` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segundo_desafio`.`status_orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segundo_desafio`.`status_orcamento` ;

CREATE TABLE IF NOT EXISTS `segundo_desafio`.`status_orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `motivo` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segundo_desafio`.`orcamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segundo_desafio`.`orcamentos` ;

CREATE TABLE IF NOT EXISTS `segundo_desafio`.`orcamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientes_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `valor_total` DOUBLE(12,4) NOT NULL,
  `pdf_url` VARCHAR(500) NOT NULL,
  `status_orcamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orcamentos_clientes_idx` (`clientes_id` ASC),
  INDEX `fk_orcamentos_status_orcamento1_idx` (`status_orcamento_id` ASC),
  CONSTRAINT `fk_orcamentos_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `segundo_desafio`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentos_status_orcamento1`
    FOREIGN KEY (`status_orcamento_id`)
    REFERENCES `segundo_desafio`.`status_orcamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
